apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: gemini-flash
  namespace: kagent
spec:
  model: gemini-2.5-flash
  provider: OpenAI
  apiKeySecret: kagent-google
  apiKeySecretKey: GOOGLE_API_KEY
  openAI:
    baseUrl: http://gemini-flash-gateway.kgateway-system.svc.cluster.local:8094/v1
---
apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: gemini-pro
  namespace: kagent
spec:
  model: gemini-2.5-pro
  provider: OpenAI
  apiKeySecret: kagent-google
  apiKeySecretKey: GOOGLE_API_KEY
  openAI:
    baseUrl: http://gemini-pro-gateway.kgateway-system.svc.cluster.local:8095/v1
