---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: n8n-ingress-authz
  namespace: n8n
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: n8n
  action: ALLOW
  rules:
    - from:
        - source:
            namespaces: ["istio-system"]
    - from:
        - source:
            namespaces: ["n8n"]
    - from:
        - source:
            namespaces: ["monitoring"]
