---
# Allow external traffic to Istio ingress gateway
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-gateway-ingress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: istio-gateway
  policyTypes:
  - Ingress
  ingress:
  # Allow all external traffic to ingress gateway
  - {}
