---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-postgres-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: authentik-postgres-credentials
  dataFrom:
  - extract:
      key: "ce454922-5533-4562-a398-b469016ba67e"
