---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app agentdesktop-config
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: databases-cluster
      namespace: databases
    - name: databases-secrets
      namespace: databases
  interval: 1h
  path: ./flux/apps/base/agentdesktop/config
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: agentdesktop
  timeout: 5m
  prune: true
  wait: true
