---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: google-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
  - secretKey: Authorization
    remoteRef:
      key: "1e03f94f-1f66-4f1a-8a7c-b42501484e56"
