---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./postgres-superuser.yaml
  - ./authentik-db-role.yaml
  - ./n8n-db-role.yaml
