---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rundeck-postgres-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: rundeck-postgres-credentials
  dataFrom:
    - extract:
        key: "a99a2fab-6b02-486c-b29f-b409017fcac1"
