---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./root-ca-certificate.yaml
  - ./ca-issuer.yaml
  - ./controller-certificate.yaml
  - ./jwt-key-certificate.yaml
  - ./secretstore.yaml
  - ./merge-externalsecret.yaml
