---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./blog-agent.yaml
  - ./youtube-agent.yaml
  - ./flux-health-agent.yaml
  - ./k8s-health-agent.yaml
  - ./code-planner-agent.yaml
  - ./code-writer-agent.yaml
  - ./code-reviewer-agent.yaml
  - ./code-supervisor-agent.yaml
