---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./authentik.yaml
  - ./grafana.yaml
  - ./kagent.yaml
  - ./longhorn.yaml
  - ./n8n.yaml
  - ./rundeck.yaml
