---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rundeck-data
  labels:
    app.kubernetes.io/name: rundeck
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
