---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: agentdesktop-oauth2-proxy
  namespace: agentdesktop
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: agentdesktop-oauth2-proxy
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: "a7fb60e8-476d-42bb-93ca-b4bb01192dd3"
        property: client-id
    - secretKey: client-secret
      remoteRef:
        key: "bfac3df5-9ece-4918-9350-b4bb01193ecc"
        property: client-secret
    - secretKey: cookie-secret
      remoteRef:
        key: "b290150e-42fb-42ea-b821-b4bb011957c7"
        property: cookie-secret
